source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'erubi'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'newrelic_rpm'
gem 'rack-lineprof'
gem 'rack-mini-profiler'

group :development do
  gem 'sinatra-contrib'
end
